"""OneBot 11 协议逻辑包（零 Hermes 依赖,可独立测试）。"""

from . import (
    audit,
    context,
    dispatch,
    events,
    http_api,
    message,
    permissions,
    queue,
    tools,
    triggers,
    ws_server,
)
from .context import (
    build_agent_context,
    build_authority_reminder,
    build_dynamic_context,
    build_queue_batch_summary,
)
from .dispatch import ActiveTurn, GroupDispatcher
from .message import ParsedMessage, parse_message_segments
from .permissions import (
    ALL_TOOLS,
    CONFIG_READ_TOOLS,
    CONFIG_WRITE_TOOLS,
    CallerContext,
    ChatTarget,
    TurnBinding,
    TurnBindingStore,
    build_role_tools,
    build_trusted_users,
    chat_access_allowed,
    is_onebot_tool_name,
    parse_exact_tool_names,
    role_for_user,
)
from .queue import (
    QueueLease,
    QueueMessage,
    QueueStore,
    ReactionRecord,
    TriggerRequest,
    TurnAnchor,
)

__all__ = [
    "events",
    "http_api",
    "message",
    "permissions",
    "queue",
    "dispatch",
    "triggers",
    "audit",
    "context",
    "tools",
    "ws_server",
    "ParsedMessage",
    "parse_message_segments",
    "CallerContext",
    "ChatTarget",
    "TurnBinding",
    "TurnBindingStore",
    "QueueLease",
    "QueueMessage",
    "QueueStore",
    "TriggerRequest",
    "TurnAnchor",
    "ReactionRecord",
    "ActiveTurn",
    "GroupDispatcher",
    "build_agent_context",
    "build_queue_batch_summary",
    "build_authority_reminder",
    "build_dynamic_context",
    "ALL_TOOLS",
    "CONFIG_READ_TOOLS",
    "CONFIG_WRITE_TOOLS",
    "build_role_tools",
    "build_trusted_users",
    "chat_access_allowed",
    "is_onebot_tool_name",
    "parse_exact_tool_names",
    "role_for_user",
]
