"""OneBot 11 协议逻辑包（零 Hermes 依赖,可独立测试）。"""

from . import (
    audit,
    commands,
    config,
    confirm,
    context,
    dispatch,
    events,
    formatting,
    http_api,
    media,
    message,
    permissions,
    pi_ai,
    queue,
    tools,
    triggers,
    ws_server,
)
from .config import (
    RuntimePolicySnapshot,
    build_policy_snapshot,
    runtime_static_fingerprint,
)
from .context import AgentContextParts, build_agent_context, build_agent_context_parts
from .dispatch import ActiveTurn, GroupDispatcher
from .formatting import (
    FormattedText,
    format_onebot_text,
    unwrap_markdown_image_markers,
)
from .media import MediaDeliveryScope, normalize_media_source
from .message import ParsedMessage, parse_message_segments
from .permissions import CallerContext, ChatTarget, TurnBinding, TurnBindingStore
from .queue import (
    OperationRecord,
    OperationStart,
    QueueError,
    QueueLease,
    QueueMessage,
    QueueResetResult,
    QueueStore,
    ReactionRecord,
    TriggerRequest,
)

__all__ = [
    "events",
    "commands",
    "http_api",
    "formatting",
    "media",
    "message",
    "pi_ai",
    "permissions",
    "queue",
    "dispatch",
    "triggers",
    "confirm",
    "audit",
    "config",
    "context",
    "tools",
    "ws_server",
    "ParsedMessage",
    "parse_message_segments",
    "FormattedText",
    "format_onebot_text",
    "unwrap_markdown_image_markers",
    "MediaDeliveryScope",
    "normalize_media_source",
    "RuntimePolicySnapshot",
    "build_policy_snapshot",
    "runtime_static_fingerprint",
    "CallerContext",
    "ChatTarget",
    "TurnBinding",
    "TurnBindingStore",
    "QueueLease",
    "QueueMessage",
    "QueueResetResult",
    "QueueError",
    "ReactionRecord",
    "QueueStore",
    "TriggerRequest",
    "OperationRecord",
    "OperationStart",
    "ActiveTurn",
    "GroupDispatcher",
    "build_agent_context",
    "build_agent_context_parts",
    "AgentContextParts",
]
